global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Performance Monitor Application
  - job_name: 'performance-monitor'
    static_configs:
      - targets: ['performance-monitor:8000']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # System Metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Prometheus Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
